server:
  port: 9001 # gateway server 运行的端口

spring:
  application:
    name: gateway # 此服务的名称（注册到注册中心用）
  cloud:
    nacos:
      server-addr: 47.105.158.15:9010

    # alibaba在2020版之后不使用ribbon,这里使用loadbalancer代替,在配置文件中禁用ribbon
    loadbalancer:
      ribbon:
        enable: false

    gateway:
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        cors-configurations:
          '[/**]':

            allowed-origin-patterns: # 允许哪些网站的跨域请求 TODO 部署记得配合前端设置跨域地址
              - "*"
#            allowedOrigins: # 允许哪些网站的跨域请求
#              - "/*"
##              - ""
            allowedMethods: # 允许的跨域Ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" #允许在请求中携带的头信息
            allow-credentials: true # 是否允许携带cookie
            max-age: 360000 # 设置跨域检测有效期，有效期内浏览器不被检测，直接放行

      routes:
        - id: webservice # 路由id，自定义，只要唯一即可
          # 路由的目标地址，lb就是负载均衡，后面跟服务名称
          uri: lb://java-webservice
          predicates: # 路由断言，也就是判断请求是否符合路由规则条件
            - Path=/web/** # 这个是按照路径匹配，只要以 /web/ 开头就符合要求
        # 同理加入论坛模块后同样设置论坛服务，todo